#서버 포트 설정
server:
    port: 8081

#database 연동 설정
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 080401familyrome*
    thymeleaf:
        cache: false

    #jpa 설정
    #이 부분은 mysql 버전 8에선 생략
    jpa:
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update
